language: python

python:
- '2.7'

branches:
  only:
    - master

before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.8.zip -nv
- unzip -q google_appengine_1.9.8.zip
- sudo ln -s `pwd`/google_appengine /usr/local/google_appengine
- sudo ln -s `pwd`/google_appengine/dev_appserver.py /usr/local/bin/dev_appserver.py
- npm install karma

install: pip install -r requirements.txt
script: ./run_tests.sh
script: karma start --browsers Phantom.js --single-run config/karma.conf.js
