language: python

python:
- '2.7'

branches:
  only:
    - master

env:
  secure: "BX2cDXNfN3TfiBeWuEvPZ9iA9mtL4FZXaAeUP22mwChlWRFCDPdfO+MP8KbdM7xLGcKsPVIk10gqij+I+l79K3QPZoaKc118EhyGAsk2BFJI/tdYCrTHkFzQ7s0xBw2AClxRk/qaWNhCzwIjXRABG6rcXggRvh8XWFbhDCc0B54="

before_script:
- wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.8.zip -nv
- unzip -q google_appengine_1.9.8.zip
- sudo ln -s `pwd`/google_appengine /usr/local/google_appengine
- sudo ln -s `pwd`/google_appengine/dev_appserver.py /usr/local/bin/dev_appserver.py
- npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

install: pip install -r requirements.txt

script:
- ./run_tests.sh
- ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS config/karma.conf.js

after_success:
- python update.py
- /usr/local/google_appengine/appcfg.py --env_variable=DEBUG:False --oauth2_refresh_token=$GAE_OAUTH_TOKEN update .
