application: geaden-main
version: stage
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /templates
  static_dir: templates

- url: /data
  static_dir: data

- url: /static
  static_dir: static

- url: .*
  script: geaden.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

builtins:
- remote_api: on
