application: geaden-main
version: test
runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  DEBUG: True

handlers:
- url: /favicon\.ico
  static_files: static/img/favicons/favicon.ico
  upload: static/img/favicon\.ico

- url: /templates
  static_dir: templates

- url: /data
  static_dir: data

- url: /static
  static_dir: static

- url: /edit
  script: geaden.app
  login: admin

- url: /
  script: geaden.app

- url: .*
  script: geaden.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?\.DS_Store$
- ^\.gitignore$
- ^\.travis.yml$
- ^\.git$
- ^libs$
- ^(.*/)?\.zip$
- ^google_appengine$
- ^node_modules$

builtins:
- remote_api: on
